name: "Build project"
on:
  pull_request:
  push:
jobs:
  build:
    name: "Publish binaries"
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - os: ubuntu-latest
            artifact_name: game.out
          - os: macos-latest
            artifact_name: game.out
          - os: windows-latest
            artifact_name: game.exe
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install dependencies (ubuntu)
      if: matrix.config.os == 'ubuntu-latest'
      id: install-deps
      run: |
        sudo apt-get update
        sudo apt-get install -y pkg-config mesa-common-dev libopengl-dev

    - name: Build project
      id: build-project
      run: |
        make
    
    - name: Release project
      id: release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/release/${{ matrix.artifact_name }}
        asset_name: ${{ matrix.asset_name }}
        tag: ${{ github.ref }}

    # - name: Release game
    #   uses: softprops/action-gh-release@v1
    #   with:
    #     name: Game
    #     tag_name: release
    #     body: |
    #       2 fruity 4 you game binaries

    #     token: ${{ secrets.GITHUB_TOKEN }}
    #     files: |
    #       2-fruity-4-you-*
