name: "Build project"
on:
  pull_request:
  push:
jobs:
  build:
    name: "Publish binaries"
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - os: ubuntu-latest
            artifact_name: game.out
            asset_name: linux-amd64
          - os: macos-latest
            artifact_name: game.out
            asset_name: macos-amd64
          - os: windows-latest
            artifact_name: game.exe
            asset_name: windows-amd64.exe
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install dependencies (ubuntu)
      if: matrix.config.os == 'ubuntu-latest'
      id: install-deps
      run: |
        sudo apt-get update
        sudo apt-get install -y pkg-config mesa-common-dev libopengl-dev

    - name: Build project
      id: build-project
      run: |
        make

      # use with ${{ steps.short-sha.outputs.sha }}
    - name: Get short SHA
      uses: benjlevesque/short-sha@v2.1
      id: short-sha
      with:
        length: 8

    - name: Release project
      id: release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{ matrix.config.artifact_name }}
        asset_name: 2-fruity-4-you-${{ github.ref }}-${{ steps.short-sha.outputs.sha }}-${{ matrix.config.asset_name }}
        tag: ${{ github.ref }}-${{ steps.short-sha.outputs.sha }}
        overwrite: true
